//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.tests = new HashSet<test>();
        }
    
        public int client_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phonenumber { get; set; }
        public string housenumber { get; set; }
        public Nullable<int> age { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<test> tests { get; set; }
    }
}
