//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff1
    {
        public staff1()
        {
            this.tests = new HashSet<test>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public int a_level { get; set; }
    
        public virtual ICollection<test> tests { get; set; }
    }
}
